apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "traefik"
    # traefik.frontend.rule.type: PathPrefixStrip
    # traefik.frontend.passHostHeader: "false"
spec:
  rules:
  - http:
      paths:
      - path: /main
        backend:
          serviceName: simple-web-service
          servicePort: 80
      # - path: /nginx
      #   backend:
      #     serviceName: nginx
      #     servicePort: 80
