apiVersion: v1
kind: Service
metadata:
  name: simple-web-service
  labels:
    run: simple-web-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    run: simple-web-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-service
spec:
  selector:
    matchLabels:
      run: simple-web-service
  replicas: 2
  template:
    metadata:
      labels:
        run: simple-web-service
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 2002
      containers:
        - name: simple-web-service
          image: __SWS_IMAGE_FULL__
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          securityContext:
            allowPrivilegeEscalation: false
